import type { NavItem } from "@/types/domain";

/**
 * Central route configuration — single source of truth for navigation.
 * Only routes that provide a meaningful screen are marked available.
 */
export const NAV_ITEMS: NavItem[] = [
  {
    id: "overview",
    label: "Overview",
    path: "/app/overview",
    icon: "layout-dashboard",
    group: "workspace",
    mobileVisible: true,
    keywords: ["dashboard", "home", "summary"],
    description: "Operational snapshot of your workspace",
    available: true,
  },
  {
    id: "inbox",
    label: "Inbox",
    path: "/app/inbox",
    icon: "inbox",
    group: "workspace",
    mobileVisible: true,
    keywords: ["conversations", "messages", "chat", "unified"],
    description: "Unified conversations across phone, email, WhatsApp and web chat",
    available: true,
  },
  {
    id: "contacts",
    label: "Contacts",
    path: "/app/contacts",
    icon: "users",
    group: "workspace",
    mobileVisible: true,
    keywords: ["leads", "people", "decision makers"],
    description: "Decision-makers, leads and customer contacts",
    available: true,
  },
  {
    id: "companies",
    label: "Companies",
    path: "/app/companies",
    icon: "building-2",
    group: "workspace",
    mobileVisible: true,
    keywords: ["accounts", "organisations", "customers"],
    description: "Customer and prospect organisations",
    available: true,
  },
  {
    id: "calls",
    label: "Calls",
    path: "/app/calls",
    icon: "phone",
    group: "customer_operations",
    mobileVisible: false,
    keywords: ["phone", "telephony", "recordings"],
    description: "Call log and demonstration telephony history",
    available: true,
  },
  {
    id: "calendar",
    label: "Calendar",
    path: "/app/calendar",
    icon: "calendar",
    group: "customer_operations",
    mobileVisible: false,
    keywords: ["schedule", "meetings", "follow ups", "demos"],
    description: "Follow-ups, demos and scheduled callbacks",
    available: true,
  },
  {
    id: "knowledge",
    label: "Knowledge",
    path: "/app/knowledge",
    icon: "book-open",
    group: "customer_operations",
    mobileVisible: false,
    keywords: ["articles", "playbooks", "docs"],
    description: "Knowledge base and response playbooks",
    available: true,
  },
  {
    id: "automations",
    label: "Automations",
    path: "/app/automations",
    icon: "workflow",
    group: "customer_operations",
    mobileVisible: false,
    keywords: ["rules", "triggers", "workflows"],
    description: "Demonstration automation rules and triggers",
    available: true,
  },
  {
    id: "analytics",
    label: "Analytics",
    path: "/app/analytics",
    icon: "bar-chart-3",
    group: "customer_operations",
    mobileVisible: false,
    keywords: ["reports", "metrics", "insights"],
    description: "Operational metrics and pipeline analytics",
    available: true,
  },
  {
    id: "team",
    label: "Team",
    path: "/app/team",
    icon: "user-cog",
    group: "manage",
    mobileVisible: false,
    keywords: ["members", "agents", "people"],
    description: "Team members and roles",
    available: true,
  },
  {
    id: "integrations",
    label: "Integrations",
    path: "/app/integrations",
    icon: "plug",
    group: "manage",
    mobileVisible: false,
    keywords: ["connectors", "providers", "api"],
    description: "Connected providers and integration status",
    available: true,
  },
  {
    id: "settings",
    label: "Settings",
    path: "/app/settings",
    icon: "settings",
    group: "manage",
    mobileVisible: false,
    keywords: ["preferences", "configuration"],
    description: "Workspace preferences",
    available: true,
  },
  {
    id: "billing",
    label: "Billing",
    path: "/app/billing",
    icon: "credit-card",
    group: "manage",
    mobileVisible: false,
    keywords: ["plan", "invoice", "subscription"],
    description: "Plan and demonstration billing",
    available: true,
  },
  {
    id: "audit_log",
    label: "Audit log",
    path: "/app/audit-log",
    icon: "scroll-text",
    group: "manage",
    mobileVisible: false,
    keywords: ["history", "events", "compliance"],
    description: "Audit event history",
    available: true,
  },
];

export const NAV_GROUPS: { id: "workspace" | "customer_operations" | "manage"; label: string }[] = [
  { id: "workspace", label: "Workspace" },
  { id: "customer_operations", label: "Customer operations" },
  { id: "manage", label: "Manage" },
];

export const MOBILE_NAV_IDS = NAV_ITEMS.filter((n) => n.mobileVisible).map((n) => n.id);

export function getNavItem(id: string): NavItem | undefined {
  return NAV_ITEMS.find((n) => n.id === id);
}
